#!/bin/sh
trap "trap - TERM && kill -- -$$" INT TERM EXIT

tmux new -d -s convai 'cd /root/convai/models/drqawrapper/; /bin/sh -c "./run_server"' \; \
    new-window -d 'cd /root/convai/models/nqg/sentence/; th online_translate.lua' \; next-window \; \
    new-window -d 'cd /root/convai/; THEANO_FLAGS=floatX=float32 python model_selection_zmq.py' \; next-window \; \
    new-window -d 'cd /root/convai/; THEANO_FLAGS=floatX=float32 python bot_zmq.py' \; next-window \; \
    attach \;

