#!/bin/bash

# download the data files here, and install any dependencies
location_base="http://132.206.3.23:8030/"
hred_twitter_model="twitter_model.zip"
hred_reddit_model="reddit_model.zip"
hred_nicolas_model="reddit-bpe5k_exp2.zip"


echo "-------Downloading models-----------"
wget "$location_base$hred_twitter_model"
unzip "$hred_twitter_model"

wget "$location_base$hred_reddit_model"
unzip "$hred_reddit_model"

wget $location_base$hred_nicolas_model"
unzip "$hred_nicolas_model"

echo "-------Models downloaded-----------"
